version: "3.4"

services:
  database:
    container_name: project101_database
    image: postgres:14.5
    restart: always
    ports:
      - 5532:5432
    networks:
      - project101_net
    volumes:
      - project101_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project101_java
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  project101_net:
    name: project101_net
    driver: bridge

volumes:
  project101_database_data:
    name: project101_database_data
    driver: local
