version: "3.4"

services:
  database:
    container_name: project101_database
    image: jeanbarcellos/project101_database
    restart: always
    ports:
      - 5532:5432
    networks:
      - project101_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project101_java

  backend-java:
    container_name: project101_backend-java
    image: jeanbarcellos/project101_backend-java
    depends_on:
      - database
    ports:
      - 8081:8080
    networks:
      - project101_net
    environment:
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=project101_java
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  frontend-reactjs:
    container_name: project101_frontend-reactjs
    image: jeanbarcellos/project101_frontend-reactjs
    networks:
      - project101_net
    ports:
      - 8082:80

networks:
  project101_net:
    name: project101_net
    driver: bridge
